### ISSUE TITLE
Nodes are not editable in symfony admin after migration

### ISSUE THREAD

**Issue by ildikototh** [dantleech/phpcr-migrations-bundle#7]
I wanted to migrate some pages ( there is a reason why I can't use fixtures) but the migration allowed me to create just a  simple node, which fails when I run my tests ( that expects a  defined childnode ( like SinglePage)) Also if you add a  node, that node is not editable in the symdfony admin side. 
`$session->getRootNode()->addNode('hello');`

**Comment by dantleech** [comment]
This is because you are presumably using PHPCR-ODM in your application.

In order for a node to be recognized by PHPCR-ODM it must have the `phpcr:class` and `phpcr:classparents` properties.

If you really must create Documents in your migrations you should use the `ContainerAwareInterface` and get the document manager - but this is not advised as the whole point of migrations is that each stage should upgrade the state of the previous stage, if you use documents then you are applying the state which you have in `master` branch of your VCS - not the state from Feb 5th 2014 or whatever.

Instead you could do:

```php
$node = $session->getRootNode()->addNode('hello');
// or 
$node = $session->getNode('/cms/contents/page');
$child = $node->addNode('my-new-document');
$child->setProperty('phpcr:class', 'Fqn\To\My\Document');
$child->setProperty('phpcr:classparents', []);
$child->setProperty('title', 'Whatever');
// ...
```
